# Generated by Django 4.2.1 on 2024-08-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_status_response_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
